[project]
name = "pyahmia"
version = "0.11.4"
description = "Search hidden services on the Tor network."
license = "MIT"
readme = "README.md"
authors = [
    { name = "Ritchie Mwewa", email = "hi@rly0nheart.com" }
]
requires-python = ">=3.12"
dependencies = [
    "requests-tor>=1.4",
    "update-checker>=0.18.0",
    "BeautifulSoup4>=4.13.4",
    "rich>=14.3.2",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Natural Language :: English"
]

[project.urls]
issues = "https://codeberg.org/rly0nheart/pyahmia/issues"
repository = "https://codeberg.org/rly0nheart/pyahmia"

[project.scripts]
ahmia = "pyahmia.src.cli:cli"
pyahmia = "pyahmia.src.cli:cli"

[project.optional-dependencies]
dev = [
    "black>=26.3.1",
]

[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pyahmia", "pyahmia.src", "pyahmia.src.api"]
